### ISSUE TITLE
fileCR

### ISSUE THREAD

**Issue by Dunamisss** [FrenchGithubUser/Hatt#10]
Not searching FileCR. It was working fine in the last release but in the newest release, even though FileCR has the files on there site, doing a search for them with your app, reveals nothing.

**Comment by FrenchGithubUser** [comment]
Could you tell which query you searched for ?

**Comment by FrenchGithubUser** [comment]
Thanks for reporting. The structure of the website changed. I updated the site's config. It will be fixed in the next release.
