### ISSUE TITLE
Virus? Hatt Windows Installer detected as a virus by SmartScreen and VirusTotal (Win32:MalOb-IJ [Cryp]  - malob/cryp)

### ISSUE THREAD

**Issue by crjaracarter** [FrenchGithubUser/Hatt#12]
Hi! Microsft Edge and VirusTotal flagged as a virus both windows installers, it's a false positive or something?:o

Link: https://www.virustotal.com/gui/file/2d8f9e43077a4a3fddb418f8ab83587efee86779f4cbedf03ae8406c2622da63

![screenshot-virustotal](https://user-images.githubusercontent.com/101837529/231889819-4af9f597-02b9-4554-99b9-9d0e9c7de1dd.png)

**Comment by FrenchGithubUser** [comment]
Feel free to audit the source code and to build from source. The closest to virus-like behavior could be that when it starts, it looks into the configuration folder (`~/.config/` for example), but there isn't really anything else I think.
