### ISSUE TITLE
Hatt on Windows 11 closes when attempted to search

### ISSUE THREAD

**Issue by eon-pixel** [FrenchGithubUser/Hatt#13]
Hi there! This may be a case of me not understanding, but I can't get Hatt to work. I type in a search query in the box, select any of the available categories and either pressing enter or clicking the search icon leads to Hatt just closing with no visible error.

**Comment by FrenchGithubUser** [comment]
Could you try with only 1 source at the time ? I think it might be a single source that generates an error.

Tell me if you have some sources that work, and tell me which ones don't, and for which query.

**Comment by eon-pixel** [comment]
> Could you try with only 1 source at the time ? I think it might be a single source that generates an error.
> 
> Tell me if you have some sources that work, and tell me which ones don't, and for which query.

After reinstalling, it looks like all of the sources work apart from Bilibili. That looks like an issue on my end though, as I can't access it in a browser either. Regardless, if Hatt can't contact a source, it seems to just close without indicating to the user why it has.

**Comment by FrenchGithubUser** [comment]
I think it is rather a problem with a specific source that made it crash. I tried using hatt without an internet connexion and it simply shows "no results".

For bilibili, they changed their api, so I need to fix the scraper.
