### ISSUE TITLE
Settings screen broken

### ISSUE THREAD

**Issue by c-hri-s** [FrenchGithubUser/Hatt#2]
On the settings screen none of the buttons on the left (Appearance / Custom Categories / Website logins) do anything. The screen only shows a thumnail size slider no matter what you select on the left 

(windows amd/64)

![image](https://user-images.githubusercontent.com/13216128/224005551-157c4969-9399-4fa2-bd2e-21fe2ec048e2.png)

**Comment by itsmehecker** [comment]
it works if you build it using wails but the settings are not added yet

**Comment by FrenchGithubUser** [comment]
The settings are still under development. Please do not open issues for beta builds in the future.
