### ISSUE TITLE
[Linux] X Window System error

### ISSUE THREAD

**Issue by Aiakio** [FrenchGithubUser/Hatt#20]
Whenever i try to run it on Pop!_OS 22.04 i get just a blank window of hutt with an error message in the terminal saying:

```
program args :  [./hatt-linux-amd64]
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal

(WebKitWebProcess:35022): Gdk-ERROR **: 10:39:06.086: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 208 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by FrenchGithubUser** [comment]
are you using an nvidia graphics card ? If yes, it is likely to be the source of the problem.

This might get you on the right path : 

https://askubuntu.com/questions/893922/ubuntu-16-04-gives-x-error-of-failed-request-badvalue-integer-parameter-out-o

You might also want to ask chatGPT about it. Here is what it gave me : 

Try first to update you system (apt update/upgrade)

Then clear webkit's cache : `rm -rf ~/.cache/WebKit`

**Comment by Aiakio** [comment]
Indeed i have a nvidia card. Clearing cache worked. thank you. :)
