### ISSUE TITLE
Application crashing upon searching when the nsfw category is ticked on

### ISSUE THREAD

**Issue by Clueeng** [FrenchGithubUser/Hatt#21]
The title says it all

**Comment by FrenchGithubUser** [comment]
could you tell me if you added some website credentials (in the settings) and what query you used ?

**Comment by bru4375** [comment]
the issue is also occurring to me, it happens with whatever search I do

**Comment by bru4375** [comment]
Did some testing and looks like simpcity is causing the issue here, even with my credentials is causing the crash!

**Comment by FrenchGithubUser** [comment]
I could not replicate a crash with simpcity. However there was a crash with coomer. Creating a new release now.

Please let me know if the crash still persists after that
