### ISSUE TITLE
9anime and zoro changed their domains

### ISSUE THREAD

**Issue by Jai707** [FrenchGithubUser/Hatt#23]
its now aniwave.to for 9anime and zorohd.to for zoro
can you change the base url of these sites

**Comment by FrenchGithubUser** [comment]
updated, will be available in the next release

**Comment by fakebhai** [comment]
> its now aniwave.to for 9anime and zorohd.to for zoro
> can you change the base url of these sites

it's actually kaido.to and aniwatch.to for zoro or at least more closer to previous one.
