### ISSUE TITLE
Add My Abandonware

### ISSUE THREAD

**Issue by 0Ha16wA5** [FrenchGithubUser/Hatt#29]
link: https://www.myabandonware.com/

**Comment by FrenchGithubUser** [comment]
Is it recommended by some communities in a wiki or something similar ?

As this site provides executables, they should be trusted

**Comment by FrenchGithubUser** [comment]
Seems good enough indeed. The source will be added, either by me or someone who wants to open a PR

**Comment by LeopoldoMoreno** [comment]
So after a bit of messing around, I was able to get a JSON for this created, but we run into an issue where the default gocolly collector timeout of 10 seconds is to short for this website. The average return seems ~15-25 seconds. I am unsure if @FrenchGithubUser wants to increase the collectors timeout, though it may help with slower sites in general. 

The JSON if you wish to test it before committing to any changes. 

my-abandonware.json 
`{
    "name": "my-abandonware",
    "categories": [
        "pc_games",
        "console_games"
    ],
    "search": {
        "url": "https://www.myabandonware.com/search/q/",
        "spaceReplacement": "+",
        "itemKeys": {
            "root": ".itemListGame",
            "name": ".c-item-game__name",
            "thumbnail": {
                "key": ".c-item-game img",
                "attribute": "src",
                "appendToSiteUrl": true
            },
            "link": ".c-item-game__name",
            "metadata": {
                "type": ".c-item-game__platforms"
            }
        }
    }
}`

**Comment by FrenchGithubUser** [comment]
Thanks, I'll take a look at the PR
