### ISSUE TITLE
Audiobook source

### ISSUE THREAD

**Issue by ItsNoted** [FrenchGithubUser/Hatt#3]
The audiobook source is listen only no downloads. Not ideal. What about adding Audiobook Bay?

Most of the sources are trash. Websites filled with ads and popups. Uninstalled.

**Comment by FrenchGithubUser** [comment]
The current audiobook sources allow you to stream. However, it is simple mp3 files being downloaded in your browser, they can be easily downloaded with jDownloader2. I'll add a guide.

I'll also add audiobookbay
