### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by thoklo** [FrenchGithubUser/Hatt#30]
Virustotal shows Malware
https://www.virustotal.com/gui/file/9145e2fbc3869632b9c5568c6c1ce56da1813f20bb07b6300f8f8f3ff4de0545
https://www.virustotal.com/gui/file/e29004459dd9fb5a69460328d86a5e9b7f1a8b35b9972f16ebd5f81fe6141f83

**Comment by FrenchGithubUser** [comment]
I am not sure what exactly is flagged there.

However, feel free to look at the source code and recompile hatt yourself. I did not introduce any malicious code.
