### ISSUE TITLE
chrome detects virus in latest version

### ISSUE THREAD

**Issue by Loser02** [FrenchGithubUser/Hatt#44]
![image](https://github.com/FrenchGithubUser/Hatt/assets/127698874/c71e52b3-3554-4dff-b070-99cbba1f8b97)
![image](https://github.com/FrenchGithubUser/Hatt/assets/127698874/fd54e125-76e8-479b-936e-1eaa5d100e58)

**Comment by Loser02** [comment]
Updated the windows one i had already installed and windows automatically deleted the software without even asking me

**Comment by Loser02** [comment]
older version works btw

**Comment by FrenchGithubUser** [comment]
Please have a look at the previous issues. 

This is likely a false flag from your anti-virus program. The whole source code is available for inspection and you can build Hatt from source
