### ISSUE TITLE
Malware warnings - Trying to understand

### ISSUE THREAD

**Issue by drjedd** [FrenchGithubUser/Hatt#45]
Hello, the latest windows installer and the exe itself light up like a christmas tree (pun intended) with Defender, Malwarebyte, Kaspersky...

https://opentip.kaspersky.com/46FDEAD1C40748BD5FB71E267F57DA17CC927E78DC8F2265DE7F593E9F38690F/results?tab=upload

Is this a false positive or explainable somehow?

**Comment by FrenchGithubUser** [comment]
please read the previous issues
