### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Chipsum** [FrenchGithubUser/Hatt#49]
Hi
What file should I use to translate the app

**Comment by FrenchGithubUser** [comment]
Could you clarify what you want to do ?

Do you want to use the app with a translation, or do you want to translate it yourself to add a new translation ?

**Comment by Chipsum** [comment]
@FrenchGithubUser 
To contribute.

**Comment by Chipsum** [comment]
To add a new translation ..
Pour Ajouter ..

**Comment by FrenchGithubUser** [comment]
You have to create a folder in `frontend/src/i18n` with the language code of your choice, then copy-paste the `index.js` file from another language to have a template and translate the words
