### ISSUE TITLE
Sign the app please

### ISSUE THREAD

**Issue by Chipsum** [FrenchGithubUser/Hatt#50]
Hi, 
Add signature as it's one of the reasons why it keeps getting detected by antiviruses.
Check this report to understand what's going on, MicrosoftEdgeWebview2Setup.exe is probably the highest reason.
[https://www.hybrid-analysis.com/sample/46fdead1c40748bd5fb71e267f57da17cc927e78dc8f2265de7f593e9f38690f/658ea25bb7bf2a00eb04f043](url)
Have a look at Malicious Indicators.

**Comment by FrenchGithubUser** [comment]
Yea indeed, adding a signature should help with this issue. However, I don't have much time these days and windows is not my priority (linux is the first supported OS for Hatt).

If someone interested in this comes by, feel free to have a closer look
