### ISSUE TITLE
Add support for igg games 

### ISSUE THREAD

**Issue by soredake** [FrenchGithubUser/Hatt#52]
Would be nice if support for igg games was added.

**Comment by jeregon1** [comment]
that site is not recommended by the majority of the community, you should be aware there have been issues with it.
Read this: https://www.reddit.com/r/Piracy/comments/ttkcit/friendly_reminder_to_stay_away_from_igggames/

**Comment by hhoneeyy** [comment]
malware site

**Comment by FrenchGithubUser** [comment]
Indeed, this site will not be added as it is not trusted
