### ISSUE TITLE
Suggest: Remove RSLOAD from database.

### ISSUE THREAD

**Issue by anonfoxer2** [FrenchGithubUser/Hatt#60]
Suggest: Remove RSLOAD from database.

Reason: [RSLOAD is now considered unsafe](https://fmhy.net/unsafesites#software-app-sites), as I am currently in the unfortunate process of realizing for myself.

**Comment by FrenchGithubUser** [comment]
It has been removed in the code, but not in the latest release yet. See : https://github.com/FrenchGithubUser/Hatt/issues/59
