### ISSUE TITLE
libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Heus-Sueh** [FrenchGithubUser/Hatt#7]
![image](https://user-images.githubusercontent.com/98482469/229823369-9da2159a-391e-481b-8bb7-6f05bf4648a8.png)

**Comment by Heus-Sueh** [comment]
I am on Fedora Silverblue and i downloaded hatt from the releases tab

**Comment by Heus-Sueh** [comment]
I managed to run the program
![image](https://user-images.githubusercontent.com/98482469/229876484-e04956a3-437d-45b8-a3a2-cfb5187afaad.png)
I had to install this dependency in the arch linux container for the program to be able to open
![image](https://user-images.githubusercontent.com/98482469/229876710-5632253e-a276-4079-91f1-7d904435adbe.png)

**Comment by FrenchGithubUser** [comment]
Nice !

could you just write which command you had to run in case some others come across the issue ?

**Comment by Heus-Sueh** [comment]
> Nice !
> 
> could you just write which command you had to run in case some others come across the issue ?

in this case I used an AUR Helper, `paru webkit2gtk`, `sudo pacman -S webkit2gtk` should work too

**Comment by FrenchGithubUser** [comment]
`pacman` is not an AUR helper, but paru is. `yay -S webkit2gtk` should also work. Thanks

**Comment by Heus-Sueh** [comment]
> `pacman` is not an AUR helper, but `paru` is. `yay -S webkit2gtk` should also work. Thanks

yeah i know i just spelled it wrong lol, would this be the [dependency](https://packages.fedoraproject.org/pkgs/webkitgtk/webkit2gtk4.0/)  for fedora?

**Comment by FrenchGithubUser** [comment]
yes I think it would be a dependency. However, there shouldn't really be any dependency other than what should already be in the OS. I'll investigate later
